/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as VisuallabsRouteImport } from './routes/visuallabs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const VisuallabsRoute = VisuallabsRouteImport.update({
  id: '/visuallabs',
  path: '/visuallabs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/areas': typeof AreasRoute
  '/chat': typeof ChatRoute
  '/downloads': typeof DownloadsRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/professor': typeof ProfessorRoute
  '/visuallabs': typeof VisuallabsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/areas': typeof AreasRoute
  '/chat': typeof ChatRoute
  '/downloads': typeof DownloadsRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/professor': typeof ProfessorRoute
  '/visuallabs': typeof VisuallabsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/areas': typeof AreasRoute
  '/chat': typeof ChatRoute
  '/downloads': typeof DownloadsRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/professor': typeof ProfessorRoute
  '/visuallabs': typeof VisuallabsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aluno'
    | '/areas'
    | '/chat'
    | '/downloads'
    | '/games'
    | '/login'
    | '/professor'
    | '/visuallabs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aluno'
    | '/areas'
    | '/chat'
    | '/downloads'
    | '/games'
    | '/login'
    | '/professor'
    | '/visuallabs'
  id:
    | '__root__'
    | '/'
    | '/aluno'
    | '/areas'
    | '/chat'
    | '/downloads'
    | '/games'
    | '/login'
    | '/professor'
    | '/visuallabs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunoRoute: typeof AlunoRoute
  AreasRoute: typeof AreasRoute
  ChatRoute: typeof ChatRoute
  DownloadsRoute: typeof DownloadsRoute
  GamesRoute: typeof GamesRoute
  LoginRoute: typeof LoginRoute
  ProfessorRoute: typeof ProfessorRoute
  VisuallabsRoute: typeof VisuallabsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visuallabs': {
      id: '/visuallabs'
      path: '/visuallabs'
      fullPath: '/visuallabs'
      preLoaderRoute: typeof VisuallabsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunoRoute: AlunoRoute,
  AreasRoute: AreasRoute,
  ChatRoute: ChatRoute,
  DownloadsRoute: DownloadsRoute,
  GamesRoute: GamesRoute,
  LoginRoute: LoginRoute,
  ProfessorRoute: ProfessorRoute,
  VisuallabsRoute: VisuallabsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
